name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install npm packages
        working-directory: ./adam-swanson-site
        run: npm i
        
      - name: Install Angular CLI
        run: sudo npm i -g @angular/cli@11.0.6 > /dev/null
  
      - name: Build for production
        working-directory: ./adam-swanson-site
        run: ng build --prod
      
      - name: Deploy to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'adam-swanson-site/dist/adam-swanson-site'
          destination_dir: ''
